baseURL: https://demimarathondeblainville.com
languageCode: fr-CA
DefaultContentLanguage: fr
title: Le Demi-Marathon de Blainville
Author:
  name: Louis-Olivier Brassard
  email: louis@corsaire-chaparral.org

theme: hugo-theme-dmb

# Markup
markup:
  goldmark:
    renderer:
      unsafe: true

# Theme-related config

######################## default configuration ####################
# post pagination
paginate: "99"
# post excerpt
summaryLength: "10"
# disqus short name
disqusShortname: "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages: [en] # desable language from here

params:
  bg_image: /images/backgrounds/landing-bg.jpg

  # Enable 'Inscription' section
  enableInscription: false

  # logo which goes in the navbar
  logo: /images/logo-navbar.png
  logo_ration: 3.19
  ############################# Plugins ##############################
  plugins:
    # CSS Plugins
    css:
    - link: "lib/slick/slick.css"
    - link: "lib/animate/animate.css"
    - link: "lib/venobox/venobox.css"
    - link: "lib/themify-icons/themify-icons.css"
    - link: "lib/aos/dist/aos.css"
    - link: "fonts/kelson/stylesheet.css"
    - link: "fonts/harris/stylesheet.css"

    # JS Plugins
    js:
    - link: "lib/jQuery/jquery.min.js"
    - link: "lib/bootstrap/js/bootstrap.bundle.min.js"
    - link: "lib/slick/slick.min.js"
    - link: "lib/venobox/venobox.min.js"
    - link: "lib/filterizr/jquery.filterizr.min.js"
    - link: "lib/scrolldir/dist/scrolldir.min.js"
    - link: "lib/scrollama/build/scrollama.min.js"

  # snipcart
  snipcart:
    publicApiKey: "MGI1OGExOGUtMjU4Yi00MGI4LTljM2EtYTcyNjhlYjA0YzEzNjM3MTg1MDE1OTA0NTUyODE3"

  # contact info
  address: >
    **Parc Équestre**<br>
    1025 Chemin du Plan-Bouchard<br>  
    Blainville (QC)<br>
    J7C 3B9

  mobile: ""
  email: "demimarathon@corsaire-chaparral.org"
  # contact form action
  contact_form_action: "" # contact form works with https://formspree.io
  # Google Analitycs
  google_analitycs_id: "" # your id
  # top header
  top_header: false
  
  preloader:
    enable: true
    preloader: "images/icons8-running-96.png" # use jpg, png, svg or gif format.


  # Subscription
  subscription:
    enable: true
    # mailchimp subsciption
    subscription_form_action: "https://campagnes.demimarathondeblainville.com/form/submit?formId=9" # replace this url with yours

  # google map
  map:
    enable: false
    gmap_api: ""
    map_latitude: ""
    map_longitude: "a"
    map_marker: "images/marker.png"

  ############################# social site ########################
  social:
  - title: "facebook"
    icon: "ti-facebook" # themify icon : https://themify.me/themify-icons
    link: "https://www.facebook.com/DemiMarathonDeBlainville/"
#  - title: "twitter"
#    icon: "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#    link: "#"
#  - title: "instagram"
#    icon: "ti-instagram" # themify icon : https://themify.me/themify-icons
#    link: "#"
#  - title: "github"
#    icon: "ti-github" # themify icon : https://themify.me/themify-icons
#    link: "#"
#  - title: "linkedin"
#    icon: "ti-linkedin" # themify icon : https://themify.me/themify-icons
#    link: "#"


############################## navigation ###############################
menu:
  # main menu
  main:

  #Info
  - name: "Info"
    URL: "a-propos"
    weight: 10
    hasChildren: true

  - parent: "Info"
    name: "Horaire"
    URL: "horaire"
    weight: 11
  - parent: "Info"
    name: "COVID-19"
    URL: "covid19-passeport-vaccinal"
    weight: 12
  - parent: "Info"
    name: "Commanditaires"
    URL: "commanditaires"
    weight: 13
  - parent: "Info"
    name: "Résultats"
    URL: "/resultats/"
    weight: 14
  - parent: "Info"
    name: "Marche CMA"
    URL: "championnat-canadien-masters"
    weight: 15
  - parent: "Info"
    name: "Nous joindre"
    URL: "contact"
    weight: 16

  # Parcours
  - weight: 20
    name: "Parcours"
    hasChildren: true
    URL: "/parcours/"
  - parent: "Parcours"
    name: "21,1 km"
    URL: "/parcours/21-km/"
    weight: 1
  - parent: "Parcours"
    name: "10 km"
    URL: "/parcours/10-km/"
    weight: 2
  - parent: "Parcours"
    name: "5 km"
    URL: "/parcours/5-km/"
    weight: 3
  - parent: "Parcours"
    name: "2 km"
    URL: "/parcours/2-km/"
    weight: 4
  - parent: "Parcours"
    name: "1 km"
    URL: "/parcours/1-km/"
    weight: 5
#  - parent: "Parcours"
#    name: "3 km marche athlétique"
#    URL: "/parcours/3-km-marche-athletique/"
#    weight: 6
  - parent: "Parcours"
    name: "5 km marche athlétique"
    URL: "/parcours/5-km-marche-athletique/"
    weight: 6


  - name: "Bénévoles"
    URL: "benevoles"
    weight: 30


  # footer menu
  footer1:
  - name: "Horaire"
    URL: "horaire"
    weight: 11
  - name: "Parcours"
    URL: "parcours"
    weight: 12
  - name: "Bénévoles"
    URL: "benevoles"
    weight: 13
  - name: "Commanditaires"
    URL: "commanditaires"
    weight: 14
  - name: "Guides"
    URL: "guides"
    weight: 15
  footer2:
  - name: "Nous joindre"
    URL: "contact"
    weight: 21
  - name: "Politique de confidentialité"
    URL: "confidentialite"
    weight: 22
Languages:
  ################################### English language #####################################
  en:
    languageName: "En"
    languageCode: "en-CA"
    weight: 1
    home: "Home"
    # copyright
    copyright: "&copy; 2021 Le Demi-Marathon de Blainville"
  ################################### French language #####################################
  fr:
    languageName: "Fr"
    languageCode: "fr-CA"
    weight: 2
    home: "Accueil"
    # copyright
    copyright: "&copy; 2021 Le Demi-Marathon de Blainville"
